pid = /var/run/stunnel.pid
foreground = yes

[mqtts]
client = yes
accept = 127.0.0.1:1883
connect = iot63018734.azure-devices.net:8883
cert = /certs/device.crt
key = /certs/device.key
sni = iot63018734.azure-devices.net